version: '3.8'

services:
        cicd_web:
                build: ./web
                container_name: cicd_web
                restart: always
                command: ["/bin/bash","-c","uwsgi --ini uwsgi.ini"]
                volumes:
                        - web_data:/web/pdfreader_test
                ports:
                        - "8001:8001"
                environment:
                        - PYTHONUNBUFFERED=TURE
        cicd_nginx:
                build: ./nginx
                container_name: cicd_nginx
                restart: always
                volumes:
                        - web_data:/web/pdfreader_test
                ports:
                        - "80:80"
                depends_on:
                        - cicd_web
volumes:
        web_data:
