version: '3.8'

services:
        pdf_web:
                build: ./web
                container_name: pdf_web
                restart: always
                command: ["/bin/bash","-c","uwsgi --ini uwsgi.ini"]
                
                ports:
                        - "8001:8001"
                environment:
                        - PYTHONUNBUFFERED=TURE
        pdf_nginx:
                build: ./nginx
                container_name: pdf_nginx
                restart: always
                
                ports:
                        - "80:80"
                depends_on:
                        - pdf_web

