# Generated by Django 4.0.6 on 2022-07-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
